#ifndef DATASTRUCTURES_GLOBAL_H
#define DATASTRUCTURES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATASTRUCTURES_LIBRARY)
#  define DATASTRUCTURES_EXPORT Q_DECL_EXPORT
#else
#  define DATASTRUCTURES_EXPORT Q_DECL_IMPORT
#endif

#endif // DATASTRUCTURES_GLOBAL_H
